### ISSUE TITLE
TagDependencyHelper\\ActiveRecordHelper' not found

### ISSUE THREAD

**Issue by obladon25** [DevGroup-ru/yii2-jstree-widget#7]
Hi.
I installed the extension, but there are some problems with the files:
Composer creates directory "yii2-tag dependency helper," but in him missing file "ActiveRecordHelper 'needs application (AdjacencyFullTreeDataAction.php - 136 line), I tried to add manually, but still receive error probably really need Composer to install.

Basic Yii2 use.
I very much need to use in Yii2 "jstree" What do you recommend on my problem?

Thank you very much

Sorry my bad english.

**Comment by fps01** [comment]
@obladon25 Thanks for a bug report!
We will fix it in few days. Now you can install old version of tag-dependency. Just run `composer update devgroup/yii2-tag-dependency-helper "~0.0.3"`

**Comment by fps01** [comment]
@obladon25 It was fixed.
You can use a version `0.2.0`. But I recommend you to look a `dev` branch. This branch will be merged to master and tagged as `1.0.0`. It has ability to work with nested sets and some another features.

**Comment by fps01** [comment]
Version `1.0.0` is available!
